name = "Yaminabe"
author = "Tandori Landori Suntori Cutleri"
version = "0.0.1Alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dad14feb55e071222a84968c6baf10983d9c6c3159056016e2e9ec0730899f7"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
