name = "Yaminabe"
author = "Tandori Landori Suntori Cutleri"
version = "0.0.1Alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12e109ef3499a44d0dcf142d0f54463326c03c31ce534bffd5c19b957bef4307"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
