name = "Yaminabe"
author = "Tandori Landori Suntori Cutleri"
version = "0.0.1Alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c8f27a778adc142bc7d20970e739ab8c5a4b431892773001297557e5d2cc036"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
